name: toodo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  #audioplayers: 
  screenshot:
  
dependencies:
  flutter:
    sdk: flutter
  #audioplayers: ^0.15.1
  #pexels: ^0.1.1

  image_gallery_saver:
  cupertino_icons: ^1.0.2
  carbon_icons: ^0.0.1+2
  hive: ^2.0.4
  path_provider:
  share: ^2.0.1
  hive_flutter: ^1.0.0
  shared_preferences: ^0.5.4
  emoji_picker: ^0.1.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_local_notifications: ^5.0.0+1
  
  

  
  
  

dev_dependencies:
  hive_generator: 
  build_runner:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - jsons/quotes.json
    - assets/achievement_bell.wav
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans/static/WorkSans-Regular.ttf
        - asset: fonts/WorkSans/WorkSans-Italic-VariableFont_wght.ttf
        - asset: fonts/WorkSans/static/WorkSans-SemiBold.ttf
          style: italic
          weight: 600
    - family: Elsie
      fonts:
        - asset: fonts/Elsie/Elsie-Regular.ttf
        - asset: fonts/Elsie/Elsie-Black.ttf
          weight: 900

    - family: AlegreyaSc
      fonts:
        - asset: fonts/Alegreya_SC/AlegreyaSC-Black.ttf
        - asset: fonts/Alegreya_SC/AlegreyaSC-Medium.ttf
          weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
